### ISSUE TITLE
readCancelled on collecting second payment.

### ISSUE THREAD

**Issue by divyesh-savaliya** [capacitor-community/stripe#346] opened 2024-04-12 08:58 UTC
**Platform**

- [ ] Web
- [X] iOS
- [ ] Android

**Describe the bug**
`collectPaymentMethod` failed while accepting another payment with error `readCancelled`

**To Reproduce**
First payment successful, when accepting payment again `collectPaymentMethod` failing with this error 

Error (read): readCancelled
`{"message":"The command was canceled.","errorMessage":"The command was canceled."}`

Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity (@capacitor-community/stripe-identity)
- [X] Terminal（@capacitor-community/stripe-terminal）

**Comment by rdlabo** [comment] 2024-04-13 07:18
Did you run `StripeTerminal.disconnectReader()` after first payment successful?

ex) https://github.com/capacitor-community/stripe/blob/main/demo/angular/src/app/terminal/terminal.page.ts#L345C11-L345C44

**Comment by rdlabo** [comment] 2024-04-13 07:24
Note) In some cases, it may be more convenient to remain connected to the READER when making successive payments. For this reason, automatic disconnection is not performed.

**Comment by divyesh-savaliya** [comment] 2024-04-14 04:19
No, i did not disconnect reader because I want to keep it connected to accept multiple payments.

**Comment by rdlabo** [comment] 2024-04-14 07:20
I have just tried it and it works fine at iOS.

```ts
(async ()=> {
  await StripeTerminal.initialize({ tokenProviderEndpoint: 'https://example.com/token', isTest: true })
  const { readers } = await StripeTerminal.discoverReaders({
    type: TerminalConnectTypes.TapToPay,
    locationId: "**************",
  });
  await StripeTerminal.connectReader({
    reader: readers[0],
  });

  // first payment
  await StripeTerminal.collectPaymentMethod({ paymentIntent: "**************" });
  await StripeTerminal.confirmPaymentIntent();

  // second payment
  await StripeTerminal.collectPaymentMethod({ paymentIntent: "**************" });
  await StripeTerminal.confirmPaymentIntent();

  await StripeTerminal.disconnectReader();
});
```

@divyesh-savaliya  If you can't get it to work, give me a small reproduction code.

**Comment by divyesh-savaliya** [comment] 2024-04-15 04:44
In the provided sample code, it disconnects the reader after each payment. However, in my case, I need to keep it connected to receive multiple payments with the same connection.

**Comment by yllaw** [comment] 2024-05-01 04:59
I am also running into this issue.

There is an issue on the official stripe ios github: https://github.com/stripe/stripe-terminal-ios/issues/300

EDIT: What is odd is that sometimes it works but most of the time it will cancel

<img width="785" alt="image" src="https://github.com/capacitor-community/stripe/assets/16358778/b3f20ef0-0653-453e-b987-2a8f471aa888">

**Comment by yllaw** [comment] 2024-06-14 16:20
Hey all, 

I believe this issue can be closed as it was a big with iOS. 

Per Stripe's official ios github: https://github.com/stripe/stripe-terminal-ios/issues/300

 `....this is a known bug with iOS 17.4.1. It should be patched if you upgrade to iOS 17.5.`

**Comment by rdlabo** [comment] 2024-08-11 02:09
Thanks for doing the research. Perhaps I couldn't reproduce it because I checked on a different iOS. I will close it as it was not a plugin issue.

**Closed by rdlabo** 2024-08-11 02:09 UTC
