### ISSUE TITLE
Request for Digital Wallets / Bank transfer features

### ISSUE THREAD

**Issue by dodomui** [capacitor-community/stripe#144] opened 2022-01-05 10:28 UTC
**Describe the solution you'd like**
Looking for following features for South-east Asia market.
1. Digital wallets for Malaysia, Singapore, and Hong Kong?
2. Bank transfer for Malaysia, FPX

**Comment by hideokamoto** [comment] 2022-01-05 12:40
Are these payment method supported by Stripe yet?

**Comment by dodomui** [comment] 2022-01-05 13:14
@hideokamoto Yes, all of them are supported by Stripe.

**Comment by rdlabo** [comment] 2022-01-06 01:55
Thanks for request. We had same request already, and We will this at future: https://github.com/capacitor-community/stripe/issues/88

But these function can't use in Japan... ( me and @hideokamoto is in Japan ).
We will start it someday, but welcome to create a pull request.

**Comment by rdlabo** [comment] 2022-01-19 01:14
@dodomui Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145

**Comment by dodomui** [comment] 2022-01-20 09:56
@rdlabo I didn't use this plugin for production.

**Comment by rdlabo** [comment] 2022-01-20 09:58
@dodomui Thanks for information! If use for production. please tell to https://github.com/capacitor-community/stripe/issues/145 !

**Comment by grzesebe** [comment] 2022-07-26 10:54
#201

**Comment by rdlabo** [comment] 2022-08-05 09:31
This is a duplicate of https://github.com/capacitor-community/stripe/issues/88 , so it is closed.

**Closed by rdlabo** 2022-08-05 09:31 UTC
Labels: enhancement
